### PR TITLE
saghul/aiouv#6: always bind local_addr before getsockname call

### PR DESCRIPTION
**Pull request by htoothrot**
Sorry about the mess on #6. I got really turned around somehow.

### CODE REVIEW

**Comment by haypo** [comment]
I don't understand the purpose of the check. What is the current behaviour? What is the error?

**Comment by saghul** [comment]
Currently if the local_addr was not given it gave an exception because getsockname would fail, as the socket was not created. Now we bind to the 'any' address.

**Comment by haypo** [comment]
It's surprising because in asyncio, the call to bind() is only made if local_addr is set. I guess that the behaviour is different in pyuv.

**Comment by htoothrot** [comment]
@haypo In asyncio, it appears the 'any' bind is implicitly done in socket.connect() (when there's no local_addr).  pyuv's start_recv() implicitly binds when there's no local_addr as well, but we landed on the explicit approach.

(Related comments on the first PR which I made a mess of and closed at #7 and traceback at #6)

**Pull request merged**
