### PR TITLE
Python 3.4 support - WIP

### PR DESCRIPTION
**Pull request by GMLudo**
As promise at FOSDEM, this is an updated version of rose, example works again.
I've integrated aiotest suite.

All test suite is broken, work in progress.

### CODE REVIEW

**Comment by GMLudo** [comment]
Hi,

Now it works with a more complex example with API-Hour + aiohttp.web Application.
I've benchmarked a little bit on one scenario, I've better performances with rose: more or less 10% speed increase compare to AsyncIO standard loop.
The very good news is that, at least for TCP and Signal handling, I've no issues with rose, it works as the AsyncIO standard loop.
If you could check the commit: https://github.com/Eyepea/rose/commit/87d2d4348ffe096ee90cc87061d607b95b423230 because I'm not sure if I close cleanly pyuv loop.

Test suites are still broken, but now the error messages are different.

**Comment by saghul** [comment]
> Hi,
> 
> Now it works with a more complex example with API-Hour + aiohttp.web Application.

Fantastic! Thanks for working on this Ludovic!

> I've benchmarked a little bit on one scenario, I've better performances with rose: more or less 10% speed increase compare to AsyncIO standard loop.
> The very good news is that, at least for TCP and Signal handling, I've no issues with rose, it works as the AsyncIO standard loop.

Great!

> If you could check the commit: Eyepea@87d2d43 because I'm not sure if I close cleanly pyuv loop.
> 

Better use UV_RUN_DEFAULT, since on Windows it may take more than one loop iteration to finish.

> Test suites are still broken, but now the error messages are different.

Onwards and upwards!

**Comment by saghul** [comment]
Victor (@haypo) told me he is also interested in working on this. I made you both collaborators, so commit like there is no tomorrow :-)

**Comment by GMLudo** [comment]
@saghul thank you a lot ;-)
Could you give us write on PyPI ?
Thank you.

**Comment by saghul** [comment]
@GMLudo what's your username on PyPI?

**Comment by GMLudo** [comment]
@saghul Ludovic.Gasc

**Comment by saghul** [comment]
@GMLudo done!

**Comment by GMLudo** [comment]
Thank you a lot @saghul for your work :-)
We'll publish quickly a release on PyPI, I want to use that in API-Hour for FrameworkBenchmark contest.

**Comment by saghul** [comment]
@GMLudo sure, go ahead!

**Pull request merged**
